# Generated by Django 3.2.3 on 2021-05-27 04:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('idProd', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('Nome', models.CharField(max_length=55)),
                ('Quantidade', models.IntegerField()),
                ('precoProduto', models.FloatField()),
                ('Descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
