# Generated by Django 3.2.3 on 2021-05-27 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('av1appbe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtos',
            name='Descricao',
            field=models.CharField(max_length=2255),
        ),
    ]
